/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module top (
  input S1,
  input S2,
  input S3,
  input S4,
  output O1,
  output O2,
  output O3
);
  assign O1 = ((S1 & S2 & ~ S3) | S4);
  assign O3 = ~ S4;
  assign O2 = S1;
endmodule
